\c techchallenge_db;

--Data generated by https://www.4devs.com.br/

-- Address data
INSERT INTO "tb_address"("street", "number", "district", "city", "state", "user_id")
VALUES ('Rua Presidente Juscelino Kubitschek', '1', 'Jardim Analândia', 'Itapecerica da Serra', 'SP', 1);

INSERT INTO "tb_address"("street", "number", "district", "city", "state", "user_id")
VALUES ('Rua Francisca Marinho', '1', 'Jardim Planalto', 'São Paulo', 'SP', 1);

INSERT INTO "tb_address"("street", "number", "district", "city", "state", "user_id")
VALUES ('Rua Santa Catarina', '1', 'Bom Pastor', 'Varginha', 'MG', 1);

-- Appliance data
INSERT INTO "tb_appliance"("name", "model", "power", "manufacturer", "user_id", "address_id")
VALUES ('TV Sala', 'Samsung Smart TV 55" OLED 4K 55S90C 2023', '40W', 'Samsung', 1, 1);

INSERT INTO "tb_appliance"("name", "model", "power", "manufacturer", "user_id", "address_id")
VALUES ('Torradeira',  'Torradeira Oster Inox Simple Life', '750W', 'Oster', 1, 1);

INSERT INTO "tb_appliance"("name", "model", "power", "manufacturer", "user_id", "address_id")
VALUES ('Aspirador', 'Aspirador de Pó Vertical Electrolux Ergorapido', '300W', 'Electrolux', 1, 1);

-- Dependent data
SET datestyle = dmy;

INSERT INTO "tb_dependent"("name", "date_of_birth", "gender", "parentage", "user_id", "address_id")
VALUES ('Henrique Hugo Matheus Freitas', '1977-01-02', 'Masculino', 'Filho', 1, 1);

INSERT INTO "tb_dependent"("name", "date_of_birth", "gender", "parentage", "user_id", "address_id")
VALUES ('Luiza Tatiane Brenda Cavalcanti', '1960-04-04', 'Feminino', 'Tia', 1, 1);

INSERT INTO "tb_dependent"("name", "date_of_birth", "gender", "parentage", "user_id", "address_id")
VALUES ('Fábio Marcelo Thomas Ferreira', '1950-01-24', 'Masculino', 'Avô', 1, 1);

INSERT INTO "tb_dependent_appliance"("appliance_id", "dependent_id")
VALUES (1, 1);