\c techchallenge_db;

--Data generated by https://www.4devs.com.br/

-- Address data
INSERT INTO "tb_address"("street", "number", "district", "city", "state")
VALUES ('Rua Presidente Juscelino Kubitschek', '1', 'Jardim Analândia', 'Itapecerica da Serra', 'SP');

INSERT INTO "tb_address"("street", "number", "district", "city", "state")
VALUES ('Rua Francisca Marinho', '1', 'Jardim Planalto', 'São Paulo', 'SP');

INSERT INTO "tb_address"("street", "number", "district", "city", "state")
VALUES ('Rua Santa Catarina', '1', 'Bom Pastor', 'Varginha', 'MG');

-- Appliance data
INSERT INTO "tb_appliance"("name", "model", "power", "manufacturer")
VALUES ('TV Sala', 'Samsung Smart TV 55" OLED 4K 55S90C 2023', '40W', 'Samsung');

INSERT INTO "tb_appliance"("name", "model", "power", "manufacturer")
VALUES ('Torradeira',  'Torradeira Oster Inox Simple Life', '750W', 'Oster');

INSERT INTO "tb_appliance"("name", "model", "power", "manufacturer")
VALUES ('Aspirador', 'Aspirador de Pó Vertical Electrolux Ergorapido', '300W', 'Electrolux');

-- Dependent data
SET datestyle = dmy;

INSERT INTO "tb_dependent"("name", "dateOfBirth", "gender", "parentage")
VALUES ('Henrique Hugo Matheus Freitas', '02/01/1977', 'Masculino', 'Filho');

INSERT INTO "tb_dependent"("name", "dateOfBirth", "gender", "parentage")
VALUES ('Luiza Tatiane Brenda Cavalcanti', '04/04/1960', 'Feminino', 'Tia');

INSERT INTO "tb_dependent"("name", "dateOfBirth", "gender", "parentage")
VALUES ('Fábio Marcelo Thomas Ferreira', '24/01/1950', 'Masculino', 'Avô');