version: '4'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: FIAPTechPostgresSQL
    volumes:
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=macapple
    ports:
      - '5432:5432'
    networks:
      - my-networks

#  app:
#    depends_on:
#      - db
#    build: .
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/techChallenge_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=macapple
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - '8081:8081'
#    networks:
#      - my-networks

networks:
  my-networks:
    driver: bridge